### ISSUE TITLE
Downloading  File Causes "A Task was canceled" Exception

### ISSUE THREAD

**Issue by WeidongShen** [OneDrive/onedrive-explorer-win#8]
When I try to download a file about 130M in size, the sample eventually throws an exception of "A Task was canceled".

Also, both download and upload files should support cancellation and progress report. Currently, only uploading large file support progress report.

**Comment by rgregg** [comment]
I'll see if I can reproduce any problems downloading files. If you have a callstack or a trace for that error occurring, it would be useful.

As for cancellation and progress reporting, you're right, both upload and download should support that. If you've got a fix for that, please feel free to submit a pull request, otherwise I'll see what I can do.

**Comment by WeidongShen** [comment]
Here is the call stack:

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OneDrive.WrappedHttpClientRequest.<GetResponseAsync>d__3.MoveNext() in c:\Work\onedrive-explorer-win-master\OneDriveSDK\Http\WrappedHttpClient.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OneDrive.ODConnection.<GetHttpResponseAsync>d__1f.MoveNext() in c:\Work\onedrive-explorer-win-master\OneDriveSDK\ODConnection.cs:line 95

**Comment by WeidongShen** [comment]
HttpClient will raise a TaskCanceledException if the send times out, and the default time out is 100 seconds. So, if you download a file large enough and it takes more than 100 seconds to complete, it will time out with the exception.

To support cancellation and progress report. Here is a link that may help you: https://canbilgin.wordpress.com/2012/06/17/download-send-request-asyncwithprogress-with-httpclient/

Thanks!

**Comment by shiroychoksey** [comment]
Yes.. Please support cancellation!

**Comment by praveenmb9752000** [comment]
How to overcome this issue. Any workaround?

**Comment by peternied** [comment]
Cancelation support was added into the [OneDrive SDK for C#](https://github.com/onedrive/onedrive-sdk-csharp) and it is also available in the [Microsoft Graph for .Net](https://github.com/microsoftgraph/msgraph-sdk-dotnet) where OneDrive is included in the supported features.
